namespace OgrenciBilgiSistemi.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PopulateCitiesTable : DbMigration
    {
        public override void Up()
        {
            Sql(@"INSERT INTO Cities VALUES ('Adana')
INSERT INTO Cities VALUES ('Adıyaman')
INSERT INTO Cities VALUES ('Afyon')
INSERT INTO Cities VALUES ('Ağrı')
INSERT INTO Cities VALUES ('Amasya')
INSERT INTO Cities VALUES ('Ankara')
INSERT INTO Cities VALUES ('Antalya')
INSERT INTO Cities VALUES ('Artvin')
INSERT INTO Cities VALUES ('Aydın')
INSERT INTO Cities VALUES ('Balıkesir')
INSERT INTO Cities VALUES ('Bilecik')
INSERT INTO Cities VALUES ('Bingöl')
INSERT INTO Cities VALUES ('Bitlis')
INSERT INTO Cities VALUES ('Bolu')
INSERT INTO Cities VALUES ('Burdur')
INSERT INTO Cities VALUES ('Bursa')
INSERT INTO Cities VALUES ('Çanakkale')
INSERT INTO Cities VALUES ('Çankırı')
INSERT INTO Cities VALUES ('Çorum')
INSERT INTO Cities VALUES ('Denizli')
INSERT INTO Cities VALUES ('Diyarbakır')
INSERT INTO Cities VALUES ('Edirne')
INSERT INTO Cities VALUES ('Elazığ')
INSERT INTO Cities VALUES ('Erzincan')
INSERT INTO Cities VALUES ('Erzurum')
INSERT INTO Cities VALUES ('Eskişehir')
INSERT INTO Cities VALUES ('Gaziantep')
INSERT INTO Cities VALUES ('Giresun')
INSERT INTO Cities VALUES ('Gümüşhane')
INSERT INTO Cities VALUES ('Hakkari')
INSERT INTO Cities VALUES ('Hatay')
INSERT INTO Cities VALUES ('Isparta')
INSERT INTO Cities VALUES ('Mersin')
INSERT INTO Cities VALUES ('İstanbul')
INSERT INTO Cities VALUES ('İzmir')
INSERT INTO Cities VALUES ('Kars')
INSERT INTO Cities VALUES ('Kastamonu')
INSERT INTO Cities VALUES ('Kayseri')
INSERT INTO Cities VALUES ('Kırklareli')
INSERT INTO Cities VALUES ('Kırşehir')
INSERT INTO Cities VALUES ('Kocaeli')
INSERT INTO Cities VALUES ('Konya')
INSERT INTO Cities VALUES ('Kütahya')
INSERT INTO Cities VALUES ('Malatya')
INSERT INTO Cities VALUES ('Manisa')
INSERT INTO Cities VALUES ('K.Maraş')
INSERT INTO Cities VALUES ('Mardin')
INSERT INTO Cities VALUES ('Muğla')
INSERT INTO Cities VALUES ('Muş')
INSERT INTO Cities VALUES ('Nevşehir')
INSERT INTO Cities VALUES ('Niğde')
INSERT INTO Cities VALUES ('Ordu')
INSERT INTO Cities VALUES ('Rize')
INSERT INTO Cities VALUES ('Sakarya')
INSERT INTO Cities VALUES ('Samsun')
INSERT INTO Cities VALUES ('Siirt')
INSERT INTO Cities VALUES ('Sinop')
INSERT INTO Cities VALUES ('Sivas')
INSERT INTO Cities VALUES ('Tekirdağ')
INSERT INTO Cities VALUES ('Tokat')
INSERT INTO Cities VALUES ('Trabzon')
INSERT INTO Cities VALUES ('Tunceli')
INSERT INTO Cities VALUES ('Şanlıurfa')
INSERT INTO Cities VALUES ('Uşak')
INSERT INTO Cities VALUES ('Van')
INSERT INTO Cities VALUES ('Yozgat')
INSERT INTO Cities VALUES ('Zonguldak')
INSERT INTO Cities VALUES ('Aksaray')
INSERT INTO Cities VALUES ('Bayburt')
INSERT INTO Cities VALUES ('Karaman')
INSERT INTO Cities VALUES ('Kırıkkale')
INSERT INTO Cities VALUES ('Batman')
INSERT INTO Cities VALUES ('Şırnak')
INSERT INTO Cities VALUES ('Bartın')
INSERT INTO Cities VALUES ('Ardahan')
INSERT INTO Cities VALUES ('Iğdır')
INSERT INTO Cities VALUES ('Yalova')
INSERT INTO Cities VALUES ('Karabük')
INSERT INTO Cities VALUES ('Kilis')
INSERT INTO Cities VALUES ('Osmaniye')
INSERT INTO Cities VALUES ('Düzce')"
);
        }
        
        public override void Down()
        {
        }
    }
}
